- packages/react-sdk-components/src/common.css
- packages/react-sdk-components/src/components/helpers/config_access.js
- packages/react-sdk-components/src/samples/FullPortal/InvalidPortal.tsx
- packages/react-sdk-components/src/samples/FullPortal/index.tsx
Showing the list of available portals from the access group for the Operator when the default portal doesn't support by SDK
> Showing list of available portals from access group for Operator

- packages/react-sdk-components/src/components/infra/Stages/Stages.tsx
- packages/react-sdk-components/src/components/template/CaseView/CaseView.tsx
- packages/react-sdk-components/src/components/template/CaseViewActionsMenu/CaseViewActionsMenu.tsx
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
Fixed the following issues:
* The Case Action buttons aren't getting localized.
* Stages on Breadcumb aren't getting localized.
* Search placeholder in ListView isn't getting localized.
Please refer BUG-808851 for more details.
> Fix Localization issues

- packages/react-sdk-components/src/components/helpers/date-format-utils.ts
- packages/react-sdk-components/src/components/helpers/formatters/common.ts
* Fixed the placeholder not being localized for date component(raised by LP).
* Please refer BUG-813490 for more details.
> Fix placeholder not being localized in Date component

- packages/react-sdk-components/src/components/field/Dropdown/Dropdown.tsx
- packages/react-sdk-components/src/components/field/RadioButtons/RadioButtons.tsx
* Fixed the issues that LP has raised for the dropdown and radio-button values aren't getting localized.
* Please refer BUG-813509 for more details.
> Fix dropdown and radio button values not getting localized

- packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
* Fixed the Attachments not working on 23.
* Pipeline was also failing because of this.
> Fix Attachments not working on 8.23 hence the Pipeline

- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Email.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/URL.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
* Fixed the tests for infinity '23.
* Seems like validation messages have changed a bit for infinity '23 hence updated accordingly.
> Fix tests for infiniy '23

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
Removed the instruction text from flow container
> Fixed instruction text displayed twice

- packages/react-sdk-components/src/components/helpers/auth.js
- packages/react-sdk-components/src/components/helpers/authManager.ts
* Keep explicit names of temporary variables within auth.js
* Eliminate clientId being used as key suffix.  Rather use a random number for this.
> Additional Auth Manager minor updates

- packages/react-sdk-components/src/components/template/DefaultForm/DefaultForm.tsx
- packages/react-sdk-components/src/components/template/MultiReferenceReadOnly/MultiReferenceReadOnly.tsx
- packages/react-sdk-components/src/components/template/SingleReferenceReadOnly/SingleReferenceReadOnly.tsx
- packages/react-sdk-components/src/components/template/WideNarrow/WideNarrowDetails/WideNarrowDetails.tsx
- packages/react-sdk-components/src/components/widget/QuickCreate/QuickCreate.tsx
Minor edits to make my comments more consistent (and easier to find)
> Make commented out interface props consistent

- packages/react-sdk-components/src/components/template/DefaultForm/DefaultForm.tsx
- packages/react-sdk-components/src/components/template/MultiReferenceReadOnly/MultiReferenceReadOnly.tsx
- packages/react-sdk-components/src/components/template/SingleReferenceReadOnly/SingleReferenceReadOnly.tsx
- packages/react-sdk-components/src/components/template/WideNarrow/WideNarrowDetails/WideNarrowDetails.tsx
- packages/react-sdk-components/src/components/widget/QuickCreate/QuickCreate.tsx
Minor edits to make my typings comments more consistent (and easier to find)
> Make commented oiut interface props consistent 8.8.12

- packages/react-sdk-components/src/components/helpers/auth.js
- packages/react-sdk-components/src/components/helpers/authManager.ts
- packages/react-sdk-components/src/samples/Embedded/EmbeddedTopLevel/index.tsx
- packages/react-sdk-components/src/samples/FullPortal/index.tsx
Direct move over of the latest authManager and auth.js files for 23.1 (along with related sample changes).
> Move latest authmanager 23.1 changes back to 8.8.20 version

- package.json
- packages/react-sdk-components/package.json
- packages/react-sdk-overrides/package.json
All automated tests pass with this PR.
> Update version to 8.8.20 and typedefs to 1.0.0

- packages/react-sdk-components/src/components/field/Currency/currency-utils.ts
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
Moving BUG-817405 from master to 8.8.20. I've tested it and it's working for all automated tests.
> Include latest updates from master branch

- assets/css/sdkStyles.css
- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
Page validation error not being displayed, added support for that.
> Alert for page messages in FlowContainer

- packages/react-sdk-components/src/components/infra/NavBar/NavBar.tsx
Some apps send 'pi-home-solid' for the Home icon
> Add icon for pi-home-solid

- packages/react-sdk-components/src/components/template/ListPage/ListPage.tsx
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/LandingPages.spec.js
* ListView data isn't proper in case of page.
* Case, etc, aren't displayed as links.
* ListView row click triggering an action.
* Added Playwright tests for Landing pages.
* Please refer US-577894 for more details.
> Fix ListView improper data, case not displayed as a link, and add playwright tests

- packages/react-sdk-components/src/components/designSystemExtension/CaseSummaryFields/CaseSummaryFields.tsx
- packages/react-sdk-components/src/components/infra/Assignment/Assignment.tsx
- packages/react-sdk-components/src/components/infra/AssignmentCard/AssignmentCard.tsx
- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
- packages/react-sdk-components/src/components/infra/MultiStep/MultiStep.tsx
- packages/react-sdk-components/src/components/infra/VerticalTabs/VerticalTabs/VerticalTabs.tsx
- packages/react-sdk-components/src/components/template/AppShell/AppShell.tsx
- packages/react-sdk-components/src/components/template/CaseView/CaseView.tsx
- packages/react-sdk-components/src/components/template/Confirmation/Confirmation.tsx
- packages/react-sdk-components/src/components/template/InlineDashboardPage/InlineDashboardPage.tsx
- packages/react-sdk-components/src/sdk-pega-component-map.js
> 8.8.20 initial updates to use getComponentFromMap

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
- packages/react-sdk-components/src/components/template/BannerPage/BannerPage.tsx
- packages/react-sdk-components/src/components/template/CaseSummary/CaseSummary.tsx
- packages/react-sdk-components/src/components/template/Confirmation/Confirmation.tsx
- packages/react-sdk-components/src/components/template/DataReference/DataReference.tsx
- packages/react-sdk-components/src/components/template/Details/Details/Details.tsx
- packages/react-sdk-components/src/components/template/Details/DetailsThreeColumn/DetailsThreeColumn.tsx
- packages/react-sdk-components/src/components/template/Details/DetailsTwoColumn/DetailsTwoColumn.tsx
- packages/react-sdk-components/src/components/template/FieldGroupTemplate/FieldGroupTemplate.tsx
- packages/react-sdk-components/src/components/template/ListPage/ListPage.tsx
- packages/react-sdk-components/src/components/template/NarrowWide/NarrowWideDetails/NarrowWideDetails.tsx
- packages/react-sdk-components/src/components/template/NarrowWide/NarrowWidePage/NarrowWidePage.tsx
- packages/react-sdk-components/src/components/template/OneColumn/OneColumnPage/OneColumnPage.tsx
- packages/react-sdk-components/src/components/template/PromotedFilters/PromotedFilters.tsx
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTable/SimpleTable.tsx
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableSelect/SimpleTableSelect.tsx
- packages/react-sdk-components/src/components/template/TwoColumn/TwoColumnPage/TwoColumnPage.tsx
- packages/react-sdk-components/src/components/template/WideNarrow/WideNarrowDetails/WideNarrowDetails.tsx
- packages/react-sdk-components/src/components/template/WideNarrow/WideNarrowPage/WideNarrowPage.tsx
- packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
- packages/react-sdk-components/src/components/widget/FileUtility/FileUtility/FileUtility.tsx
- packages/react-sdk-components/src/components/widget/QuickCreate/QuickCreate.tsx
- packages/react-sdk-components/src/components/widget/SummaryList/SummaryList.tsx
- packages/react-sdk-components/src/sdk-pega-component-map.js
- scripts/override-constants.js
8.8.20 getComponentFromMap updates for template and widget
> 8.8.20 getComponentFromMap updates for template and widget

- packages/react-sdk-components/doc/KeyReleaseUpdates.md
There are some links that don't work and/or need to be updated before this is released. But I wanted to have a PR for review and possible editing.
> Initial draft of KeyReleaseUpdates for 23.1.10

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
- packages/react-sdk-components/src/components/widget/ToDo/ToDo.tsx
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
* Fixed ToDo, etc. issues and laywright tests.
> Fix ToDo, tests, etc.

- packages/react-sdk-components/src/components/designSystemExtension/FieldGroupList/FieldGroupList.tsx
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx
- packages/react-sdk-components/src/components/widget/SummaryItem/SummaryItem.tsx
* Fix lint issues as mentioned in BUG-836501.
> Fix lint issues 

- packages/react-sdk-components/src/components/designSystemExtension/FieldGroupList/FieldGroupList.tsx
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx
- packages/react-sdk-components/src/components/widget/SummaryItem/SummaryItem.tsx
* Fix lint issues as mentioned in BUG-836501.
> Fix lint issues

- packages/react-sdk-components/src/components/helpers/simpleTableHelpers.ts
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js
* Fixed the issues mentioned in BUG-832692 & BUG-832690.
* Also, added the tests for these issues.
> Fix ListView issues and add the tests

- packages/react-sdk-components/src/components/helpers/simpleTableHelpers.ts
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js
* Fixed the issues mentioned in BUG-832692 & BUG-832690.
* Also, added the tests for these issues.
> Fix ListView issues and add tests

- packages/react-sdk-components/src/components/field/Currency/Currency.tsx
- packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
- packages/react-sdk-components/src/components/field/Email/Email.tsx
- packages/react-sdk-components/src/components/field/Integer/Integer.tsx
- packages/react-sdk-components/src/components/field/Percentage/Percentage.tsx
- packages/react-sdk-components/src/components/field/Phone/Phone.tsx
- packages/react-sdk-components/src/components/field/TextArea/TextArea.tsx
- packages/react-sdk-components/src/components/field/TextInput/TextInput.tsx
- packages/react-sdk-components/src/components/field/URL/URL.tsx
Fixed placeholder values for text input fields.
Related to issue #258
> Display placeholder values for text input fields.

- packages/react-sdk-components/src/components/field/AutoComplete/AutoComplete.tsx
- packages/react-sdk-components/src/components/field/Currency/Currency.tsx
- packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
- packages/react-sdk-components/src/components/field/Email/Email.tsx
- packages/react-sdk-components/src/components/field/Integer/Integer.tsx
- packages/react-sdk-components/src/components/field/Percentage/Percentage.tsx
- packages/react-sdk-components/src/components/field/Phone/Phone.tsx
- packages/react-sdk-components/src/components/field/RichText/RichText.tsx
- packages/react-sdk-components/src/components/field/TextArea/TextArea.tsx
- packages/react-sdk-components/src/components/field/TextInput/TextInput.tsx
- packages/react-sdk-components/src/components/field/URL/URL.tsx
- packages/react-sdk-components/src/components/field/UserReference/UserReference.tsx
Fixed placeholder values for form fields.
Related to issue https://github.com/pegasystems/react-sdk-components/issues/258
> Placeholder added for field components

- packages/react-sdk-components/src/components/field/Currency/Currency.tsx
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
fix: currency formatting display doesn't stay consistent
fix: Inline Dashboard test failure when day is Tuesday
> fix: currency formatting display doesn't stay consistent

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
* Fixed the MediaCo/embedded tests.
* Please refer BUG-846381 for more details.
> Fix MediaCo/embedded tests

- packages/react-sdk-components/src/components/field/AutoComplete/AutoComplete.tsx
- packages/react-sdk-components/src/components/field/Dropdown/Dropdown.tsx
- packages/react-sdk-components/src/components/helpers/utils.ts
> fix: Dropdown datasource

- packages/react-sdk-components/src/components/designSystemExtension/CaseSummaryFields/CaseSummaryFields.tsx
- packages/react-sdk-components/src/components/designSystemExtension/Operator/Operator.tsx
Updated Operator component to not wrap props under caseOpConfig object
> Updated operator component props object

- packages/react-sdk-components/src/components/template/CaseViewActionsMenu/CaseViewActionsMenu.tsx
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/OptionalAction.spec.js
Added function to open process flow in case view actions menu
Added playwright test
> Support Optional process flows

- packages/react-sdk-components/src/components/widget/FileUtility/FileUtility/FileUtility.tsx
* Fixed the multiple attachment issue when uploaded using Utility Panel.
* Please refer BUG-857870 for more details.
> Fix multiple attachment issue when uploaded using Utility Panel

- packages/react-sdk-components/src/components/designSystemExtension/FieldGroup/FieldGroup.tsx
- packages/react-sdk-components/src/components/field/Checkbox/Checkbox.tsx
- packages/react-sdk-components/src/components/field/Group/Group.tsx
- packages/react-sdk-components/src/components/field/Group/config-ext.json
- packages/react-sdk-components/src/components/field/Group/index.tsx
- packages/react-sdk-components/src/components/helpers/formatters/Boolean.ts
- packages/react-sdk-components/src/components/helpers/formatters/index.ts
- packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ModalViewContainer.tsx
- packages/react-sdk-components/src/components/template/DefaultForm/DefaultForm.css
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx
- packages/react-sdk-components/src/sdk-pega-component-map.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/FieldGroup.spec.js
- Field Group support has been added (Group component added in field components)
- fixed the issue "Display of boolean value inside table shows true/false"
- Date Picker inside Modal Dialog not loading
> Field Group support added

- packages/react-sdk-components/src/components/infra/Assignment/Assignment.tsx
- packages/react-sdk-components/src/components/infra/NavBar/NavBar.tsx
- packages/react-sdk-components/src/components/template/CaseSummary/CaseSummary.tsx
- packages/react-sdk-components/src/components/template/WssNavBar/WssNavBar.tsx
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/Screenflow.spec.js
Added required changes to support sub flow in React SDK
Added Playwright tests
Added Fix to Localize casetypes and Landing pages
Added Fix to Localize caseStatus in CaseSummary view
Added Fix to Localize Log off button
> Added Screenflow changes

- package.json
- packages/react-sdk-components/package.json
- packages/react-sdk-components/tests/common.js
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/CaseView.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/EmbeddedData.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/UserReference.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/FieldGroup.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/OptionalAction.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Picklist.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/URL.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/LandingPages.spec.js
- packages/react-sdk-overrides/package.json
- Package version updated to 23.1.11
- Playwright tests lint fixes
> package version update 23.1.11

- packages/react-sdk-components/src/components/template/CaseViewActionsMenu/CaseViewActionsMenu.tsx
error handling in process action
> error handling in process action

- packages/react-sdk-components/src/components/field/Currency/Currency.tsx
- packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
* This issue has been raised as the Currency & Decimal format isn't working as expected based upon the locale.
* Please refer BUG-862374 for more details.
> BUG-862374: Fix Currency & Decimal format issues

- packages/react-sdk-components/src/components/field/Group/Group.tsx
- packages/react-sdk-components/src/components/helpers/simpleTableHelpers.ts
- packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx
Issue: Add/edit modal was not opening for embedded data table with some pre processed data.
> fix: add/edit modal not working in embedded table

- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
Added style for scroll and pagination to be visible as in few cases like when list view is used in small section of page and not entire page is available, experience is not good.
> Added style to allow scroll and display pagination

- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/EmbeddedData.spec.js
* Added the Playwright tests for testing the Sorting functionality in the Table and ListView.
> Add Playwright tests for testing Sorting functionality in the Table and ListView

- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Boolean.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Currency.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Integer.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Percentage.spec.js
Updated the playwright tests for Currency, integer, percentage and boolean based on feature gap
> Updated playwrights for formfield_23

- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Boolean.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Currency.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Integer.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Percentage.spec.js
Updated the playwright tests for Currency, integer, percentage and boolean based on feature gap
> Updated Playwright tests for formfields

- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
Playwright tests for Mediaco/portal are failing because constellation version is updated.removed condition based pcore as no longer required after branching.
> removed condition based on pcore as no longer needed

- packages/react-sdk-components/src/components/designSystemExtension/CaseSummaryFields/CaseSummaryFields.tsx
- packages/react-sdk-components/src/components/infra/NavBar/NavBar.tsx
- packages/react-sdk-components/src/components/template/ListView/ListView.tsx
* Fixed minor style issues found during adoption testing.
* Fixed react duplicate keys warnings.
> Fix style issues and react warnings

- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/EmbeddedData.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Phone.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/ViewTemplates/Confirmation.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/embedded.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
* Fixed the EmbeddedData and the other tests using Phone component.
* Please refer BUG-873319 for more details.
> Fix EmbeddedData and other tests

- packages/react-sdk-components/src/components/template/DefaultForm/utils/index.ts
* Fixed the duplicate key issue in the DefaultForm component.
* Please refer BUG-873970 for more details.
> Fix duplicate keys issue in the DefaultForm component

- packages/react-sdk-components/src/components/infra/DeferLoad/DeferLoad.tsx
Added catch block as failing in instruction text test
> Added catch block as failing in instruction text test

- package-lock.json
- package.json
updated constellation version to 23.1.2
> updated constellation version to 23.1.2

- sdk-config.json
* Removed the optional settings info from sdk-config.json, as done in react-sdk repo.
> Remove optional settings info from skd-config.json

- playwright.config.js
updated playwright config to skip localization tests
> updated playwright config to skip localization tests

- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Attachment.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
- playwright.config.js
Updated tests to not wait on API response
> Updated tests to not wait on API response

- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Attachment.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
- playwright.config.js
> updated tests

- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
updating inlinedashboard and mediaco portal test
> updating inlinedashboard and mediaco portal test

- packages/react-sdk-components/src/components/widget/ToDo/ToDo.tsx
* Fixed the ToDo not loading for DigV2 and other related issue.
> Fixed ToDo not loading for DigV2 and other related issues

- .gitignore
* Git should ignore coverage reports.
> Git should ignore coverage reports

- packages/react-sdk-components/src/components/field/DateTime/DateTime.tsx
- packages/react-sdk-components/src/components/field/Phone/Phone.tsx
- packages/react-sdk-components/src/components/field/Time/Time.tsx
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/CaseView.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Date.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/DateTime.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/FieldGroup.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Phone.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Time.spec.js
- packages/react-sdk-components/tests/e2e/Digv2/LandingPages/InlineDashboard.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/embedded.spec.js
- packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js
* Fixed most of the Playwright tests.
* Optional Action and Case Ref are the ones, whic are still failing.
> Fix playwright tests

- packages/react-sdk-components/src/components/designSystemExtension/FieldValueList/FieldValueList.tsx
styling change in fieldvaluelist
> styling change in fieldvaluelist

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
> Fixed Optional Actions

- package-lock.json
- package.json
- packages/react-sdk-components/src/components/field/Phone/Phone.tsx
- packages/react-sdk-components/tests/e2e/Digv2/FormFields/Phone.spec.js
* Replaced the existing Phone comp with the mui-tel-input.
* This one is lighter in size & is more actively maintained also.
> Replace the existing Phone comp with mui-tel-input

- package-lock.json
- package.json
* Upgraded the pega/auth library.
> Upgrade pega/auth

- packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ListViewActionButtons/ListViewActionButtons.tsx
Fix error when modal submitted without filling required field
> Fix error when modal submitted without filling required field

- packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ListViewActionButtons/ListViewActionButtons.tsx
> Enabled submit post api call

- packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ListViewActionButtons/ListViewActionButtons.tsx
> Enabling submit post api call

- packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/CaseReference.spec.js
* Fixed the Case Reference test.
> Fixed Case Reference test

- packages/react-sdk-components/src/components/field/Date/Date.tsx
- packages/react-sdk-components/src/components/field/DateTime/DateTime.tsx
- packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
- packages/react-sdk-components/src/components/field/Percentage/Percentage.tsx
trigger useeffect on value change in Date, datetime, percentage and decimal
> trigger useeffect on value change

- packages/react-sdk-components/src/components/helpers/formatters/index.ts
* Fixed the handling of date values. 
* Raised by https://github.com/pegasystems/react-sdk-components/issues/442.
> Fix dates formatting

- packages/react-sdk-components/src/components/field/Currency/Currency.tsx
- packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
updated decimal to show percentage when formatter is percentage and style change in currency
> updated decimal to show percentage when formatter is percentage

- package-lock.json
- package.json
> chore: update version to 24.2.11 and bump @pega/constellationjs to 24.2.2

- packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
* Fixed the pyConfirm isn't visible issue.
> Fixed pyConfirm isn't visible

- packages/react-sdk-components/src/bridge/react_pconnect.jsx
- packages/react-sdk-components/src/components/field/ObjectReference/ObjectReference.tsx
- packages/react-sdk-components/src/components/field/ObjectReference/index.tsx
- packages/react-sdk-components/src/components/field/ObjectReference/utils.ts
- packages/react-sdk-components/src/components/field/SemanticLink/SemanticLink.tsx
- packages/react-sdk-components/src/sdk-pega-component-map.js
* Added the Object Reference component.
* Enhanced the Semantic Link component.
> Added Object Reference and enhanced Semantic Link components
