pegasystems/react-sdk-components

packages/react-sdk-components/src/bridge/helpers/sdk_component_map.ts
packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ModalViewContainer.tsx
packages/react-sdk-components/src/components/infra/View/View.tsx

This fixes the case where some infra components (that are **not** exposed for potential overriding) are rendering 
components that **can** be overridden without checking the component map to see if there is a local implementation.
Added a new helper function: getComponentFromMap and now use that in FlowContainer and ModalViewContainer to address that problem. Also, updated View component to use the new function, too.

Get components from map for infra components

---

package.json
webpack.config.js

This may not matter here but keeping aligned with react-sdk PR 378

For symmetry with react-sdk, no webpack load for .d.ts or .map files

---

packages/react-sdk-components/src/components/helpers/authManager.ts

When the new typings info was merged, the typings in the (also updated) authManager.ts aren't recognized as correct. So, this is an attempt to fix those typings. (This code works but I'm not sure why the HeadersInit type isn't recognized (other than that it doesn't seem to be in node_modules/@types though VS Code finds it via its own path.)

Attempt to address AuthManager typings

---

package.json

Setting up master for testing against 8.8. **Once that's settled**, I'll be branching master off to release/8.8.12 for future work and master will be set up to be associated with 23.1.10 release.

Use latest 8.8 - patch/2.3 Typedefs

---

packages/react-sdk-components/src/components/helpers/auth.js

(On subsequent full re auth or on browser reload)
Clean up regression with locking introduced with PR #178

Fix issue with subsequent authorize not having the session_index query arg

---

package.json
packages/react-sdk-components/src/components/helpers/authManager.ts
tsconfig.json

Note: important changes in tsconfig.json to work with new style of finding/using typedefs. (No longer copied to node_modules/https://github.com/types since that wasn't reliable.)

Get types working with newly published version

---

package.json

The 3 portal test fails. A known problem to be fixed soon. Unrelated to this change.

Update to use "prod" typedefs for 23.1.0

---

packages/react-sdk-components/src/components/infra/NavBar/NavBar.tsx

Some apps send 'pi-home-solid' for the "Home" icon

Add icon for pi-home-solid

---

packages/react-sdk-components/src/components/field/ScalarList/ScalarList.tsx
packages/react-sdk-components/src/components/infra/Containers/ViewContainer/ViewContainer.tsx
packages/react-sdk-components/src/components/infra/DashboardFilter/DashboardFilter.tsx
packages/react-sdk-components/src/components/infra/DashboardFilter/filterUtils.tsx
packages/react-sdk-components/src/components/infra/Reference/Reference.tsx
packages/react-sdk-components/src/components/template/CaseView/CaseView.tsx
packages/react-sdk-components/src/components/template/DataReference/DataReference.tsx
packages/react-sdk-components/src/components/template/Details/Details/Details.tsx
packages/react-sdk-components/src/components/template/Details/DetailsThreeColumn/DetailsThreeColumn.tsx
packages/react-sdk-components/src/components/template/Details/DetailsTwoColumn/DetailsTwoColumn.tsx
packages/react-sdk-components/src/components/template/MultiReferenceReadOnly/MultiReferenceReadOnly.tsx
packages/react-sdk-components/src/components/template/NarrowWide/NarrowWideDetails/NarrowWideDetails.tsx
packages/react-sdk-components/src/components/template/SingleReferenceReadOnly/SingleReferenceReadOnly.tsx
packages/react-sdk-components/src/components/template/WideNarrow/WideNarrowDetails/WideNarrowDetails.tsx

The current version of the typedefs don't mark some args to createComponent as optional (even though they act as optional). So, we can re-enable some typedefs by adding in the optional arguments - typically, "null, null, {}

Add "optional" args to get typedefs to work for createComponent

---

packages/react-sdk-components/src/components/designSystemExtension/CaseSummaryFields/CaseSummaryFields.tsx
packages/react-sdk-components/src/components/infra/Assignment/Assignment.tsx
packages/react-sdk-components/src/components/infra/AssignmentCard/AssignmentCard.tsx
packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
packages/react-sdk-components/src/components/infra/MultiStep/MultiStep.tsx
packages/react-sdk-components/src/components/infra/VerticalTabs/VerticalTabs/VerticalTabs.tsx
packages/react-sdk-components/src/components/template/AppShell/AppShell.tsx
packages/react-sdk-components/src/components/template/CaseView/CaseView.tsx
packages/react-sdk-components/src/components/template/Confirmation/Confirmation.tsx
packages/react-sdk-components/src/components/template/InlineDashboardPage/InlineDashboardPage.tsx
packages/react-sdk-components/src/sdk-pega-component-map.js

This initial PR to get components from the Map (rather than importing) addresses all of the component imports I've found in files (**master** branch):
- designSystemExtension directory
- infra directory
It also includes files that used to have references to component imports from **../infra**, **../field**, **../template**, and **../widget**

Initial set of replacing import with getComponentFromMap

---

packages/react-sdk-components/src/components/field/AutoComplete/AutoComplete.tsx
packages/react-sdk-components/src/components/field/Dropdown/Dropdown.tsx
packages/react-sdk-components/src/components/field/RadioButtons/RadioButtons.tsx
packages/react-sdk-components/src/components/infra/Assignment/Assignment.tsx
packages/react-sdk-components/src/components/infra/Containers/ModalViewContainer/ModalViewContainer.tsx
packages/react-sdk-components/src/components/infra/DeferLoad/DeferLoad.tsx

As of 8.8.4, passing an empty string as an argument to getDataObject breaks things. Should pass the current "context" (which can be obtained the the current PConnect's getContextName()

Mod/spr/fix get data object 8.8.20

---

packages/react-sdk-components/src/components/field/Currency/Currency.tsx
packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js

Issue: Currency formatted value doesn't staying consistent.
After implementing the fix for this bug, one of the existing tests failing due to the field value not appearing in the DOM. During debugging, it was identified that the issue is from the material-ui-currency-textfield component which we are using in Currency and Decimal component, Tried few approaches to fix the tests but nothing worked out. The failing test statements have been commented for now, and an issue has been raised on the component's GitHub page.

Fixed the readOnly mode currency formatting issue

---

packages/react-sdk-components/src/components/field/Checkbox/Checkbox.tsx

Issue: Currently React SDK Checkbox is not showing label in the UI

Checkbox label differs from constellation ui

---

packages/react-sdk-components/src/components/template/ListView/ListView.tsx
packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx

* The sorting(both ascending and descending) wasn't working as exptected, specially when Falsy(i.e. undefined, null, etc.) values are present. 
* Also, fixed the formatting by showing the dashes in case value doesn't exist in both the List and Tables.
* Please refer US-605822-1 for more details.

Fix Sorting in the List and Tables(particularly in case of Falsy values) and formatting

---

packages/react-sdk-components/src/components/field/Decimal/Decimal.tsx
packages/react-sdk-components/tests/e2e/Digv2/FormFields/Decimal.spec.js

Updated decimal component. when decimal is read only and displayed as currency, no currency symbol was displayed. After this change will be able to see currency symbol in UI.

Display currency symbol in decimal

---

packages/react-sdk-components/src/components/infra/Reference/Reference.tsx

* Fixed the data page parameters not being passed within the ListView component.
* The parameters which were referring to a field(which in turn was referring to a constant) were working, but the problem was with the parameters which were referring to a field(which in turn referring to a property).
* Please refer BUG-866299 for more details.

Fix ListView data page params not being passed issue

---

packages/react-sdk-components/tests/e2e/Digv2/FormFields/Email.spec.js
packages/react-sdk-components/tests/e2e/Digv2/FormFields/Phone.spec.js
packages/react-sdk-components/tests/e2e/Digv2/FormFields/Picklist.spec.js

* Add playwright tests for the missing scenarios in the Form Fields.
* Please refer US-611865 for more details.

Add playwright tests for missing scanrios in Form Fields

---

packages/react-sdk-components/src/components/field/UserReference/UserReference.tsx

* Fixed User Reference wasn't working as expected in Details template.
* Basically, it should be displayed as Read only in Details template, which isn't the case at the moment.
* Please refer BUG-874007 for more details

Fix User Reference not working as expected in Details template

---

packages/react-sdk-components/src/components/field/Phone/Phone.tsx
packages/react-sdk-components/tests/common.js
packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/EmbeddedData.spec.js
packages/react-sdk-components/tests/e2e/Digv2/FormFields/Phone.spec.js
packages/react-sdk-components/tests/e2e/Digv2/ViewTemplates/Confirmation.spec.js
packages/react-sdk-components/tests/e2e/MediaCo/embedded.spec.js
packages/react-sdk-components/tests/e2e/MediaCo/portal.spec.js

Current Behavior: When you enter a number on phone number which is not a required field on the form, and after clearing the phone number it is showing validation error message
Expected Behavior: Shouldn't show validation message on clear

fix: SDK-R Phone number can't clear client validation error

---

packages/react-sdk-components/tests/e2e/Digv2/FormFields/Attachment.spec.js
packages/react-sdk-components/tests/e2e/Digv2/FormFields/Email.spec.js

* Fixed some of the Playwright test.

Fixed some of the tests

---

packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx

While testing sdktest app, create dictu case and clicked on sandbox tab then got an api failure.

Added catch block with console log

---

package-lock.json
package.json
packages/react-sdk-components/src/auth.html
packages/react-sdk-components/src/components/field/CancelAlert/CancelAlert.tsx
packages/react-sdk-components/src/components/field/Dropdown/Dropdown.tsx
packages/react-sdk-components/src/components/field/RadioButtons/RadioButtons.tsx
packages/react-sdk-components/src/components/field/ScalarList/ScalarList.tsx
packages/react-sdk-components/src/components/field/UserReference/UserReference.tsx
packages/react-sdk-components/src/components/infra/Assignment/Assignment.tsx
packages/react-sdk-components/src/components/infra/Containers/FlowContainer/FlowContainer.tsx
packages/react-sdk-components/src/components/infra/Containers/FlowContainer/helpers.ts
packages/react-sdk-components/src/components/infra/DashboardFilter/DashboardFilter.tsx
packages/react-sdk-components/src/components/infra/DashboardFilter/filterUtils.tsx
packages/react-sdk-components/src/components/infra/DeferLoad/DeferLoad.tsx
packages/react-sdk-components/src/components/infra/MultiStep/MultiStep.tsx
packages/react-sdk-components/src/components/infra/RootContainer/RootContainer.tsx
packages/react-sdk-components/src/components/template/CaseView/CaseView.tsx
packages/react-sdk-components/src/components/template/Details/DynamicTabs/DynamicTabs.tsx
packages/react-sdk-components/src/components/template/FieldGroupTemplate/FieldGroupTemplate.tsx
packages/react-sdk-components/src/components/template/ListView/ListView.tsx
packages/react-sdk-components/src/components/template/ListView/utils.ts
packages/react-sdk-components/src/components/template/PromotedFilters/PromotedFilters.tsx
packages/react-sdk-components/src/components/template/SimpleTable/SimpleTable/SimpleTable.tsx
packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableManual/SimpleTableManual.tsx
packages/react-sdk-components/src/components/template/SimpleTable/SimpleTableSelect/SimpleTableSelect.tsx
packages/react-sdk-components/src/components/widget/Attachment/Attachment.tsx
packages/react-sdk-components/src/components/widget/QuickCreate/QuickCreate.tsx
packages/react-sdk-components/src/samples/Embedded/ShoppingOptionCard/index.tsx
packages/react-sdk-components/src/samples/FullPortal/index.tsx

* Upgraded typedef to 3.2.2.
* Fixed a condition in RootConatiner component which was breaking the SDK(a regression).
* Removed ts-ignore and eslint statements wherever required.

Upgraded typedef to 3.2.2, removed a bunch of ts-ignore and eslint statements

---

packages/react-sdk-components/src/components/field/Currency/Currency.tsx
packages/react-sdk-components/src/components/helpers/formatters/Currency.ts

- currency symbol to be determined based on ISO code or country code.
- Added use effect to be triggered on value property change

updated currency component to show correct currency symbol based on ISO code

---

packages/react-sdk-components/tests/e2e/Digv2/ComplexFields/DataReference.spec.js

* Fixed the DataRef playwright test.

Fixed DataRef playwright test
